baseURL       = "https://Jarpiano.github.io/habitat-pilot/"
languageCode  = "en-us"
title         = "THS Habitat For Humanity"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Events"
    url     = "events"
    weight  = 3
  [[menu.nav]]
    name    = "Contact Us"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo-ths.png"
  dateFormat = "9 JULY 2022" # Update on publishing date
  # Meta data
  description = "THS Habitat For Humanity"
  author = "Jared Baron Panares"
  
  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/nature-wallpaper.jpg"
    heading               =  "Travis High School"
    heading_line_2        = "Habitat for Humanity" #Ignore if not required
    tagline               = "Who we are"
    primary_button        = "Our Calendar"
    primary_button_url    = "events"
    secondary_button      = "Get in Touch"
    secondary_button_url  = "contact"

  [params.events]
    enable    = true
    title     = "OUR EVENTS"
    subtitle  = "We have multiple events scheduled throughout the year including virtual!"
    questions = "QUESTIONS"
    q_descriptions = "If you have a question or want to recommned an event please contact us via the methods listed in the Contacts page!"

  [params.meeting]
    enable    = true
    title     = "OUR MEETINGS"
    subtitle  = "Meetings are always Someday of each month, excluding holidays and vacations"
    notice    = "Members must come in a timely manner for attendance"
    statement = "If a member cannot attend please contact us via the methods listed on the Contact page or privately message an officer."


  [params.announcement]
    enable    = true
    title     = "ANNOUNCEMENTS"
    subtitle  = "Stay up-to-date with the club"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S MAKE A DIFFERENCE"
    primary_button      = "Apply Now"
    primary_button_url  = "contact"
    secondary_button    = "See Events"
    secondary_button_url = "events"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "11111 Harlem Road Pecan Grove, Texas 77406 United States"
      email   = "example@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Home"
          url  = "/"
        [[params.footer.sitemap.link]]
          name = "About Us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Calendar"
          url  = "events"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Credits"
        description = 'This site was built using the <a href="https://gohugo.io/" target="_blank">Hugo</a> framework using the Hugo <a href="https://github.com/StaticMania/roxo-hugo" target="_blank">roxo</a> theme and created by Jared Baron Panares'